#%RAML 1.0 NamedExample
values: 
  customers:
    - #customer 1
      id: 1
      name: Pedro
      surname: Luiz
      documentNumber: "05012375360"
      gender: M
      birthday: 1986-05-06
      email: Pedro.Luiz@gmail.com
      contact:
        telephone: (11) 98985-1551
        mobile: (11) 16155-5151
      company: IBeans
      address: 
        street: Av Paulista
        number: "202"
        complement: Apto 204
        country: Brazil
        state: São Paulo
        town: São Paulo
        zipCode: 01050-000
      acceptMarketing: true
      comments: No comment
    - #customer 2
      id: 2
      name: Paulo
      surname: Leão
      documentNumber: "50143589756"
      gender: M
      birthday: 1990-08-10
      email: Paulo.Leao@gmail.com
      contact:
        telephone: (11) 98985-1551
        mobile: (11) 16155-5151
      company: IBeans
      address: 
        street: Consolação
        number: "402"
        complement: Apto 505
        country: Brazil
        state: São Paulo
        town: São Paulo
        zipCode: 010005-000
      acceptMarketing: true
      comments: No comment